default_provider = "onepass"

[providers]
onepass = { type = "1password", vault = "Contracting Works 24SO", account = "valuegroupas.1password.com" }

[secrets]
TFSO_SOAP_APPLICATIONID = { provider = "onepass", value = "op://Contracting Works 24SO/24SevenOffice API/username" }
TFSO_SOAP_USERNAME = { provider = "onepass", value = "op://Contracting Works 24SO/24SevenOffice/email" }
TFSO_SOAP_PASSWORD = { provider = "onepass", value = "op://Contracting Works 24SO/24SevenOffice/password" }

TFSO_REST_APP_ID = { provider = "onepass", value = "op://Contracting Works 24SO/24SevenOffice REST/Application ID" }
TFSO_REST_SECRET = { provider = "onepass", value = "op://Contracting Works 24SO/24SevenOffice REST/Client Secret" }

TFSO_PAYROLL_SECRET = { provider = "onepass", value = "op://Contracting Works 24SO/24SevenOffice API Payroll/credential" }
