// Code generated by gowsdl DO NOT EDIT.

package person

import (
	"context"
	"encoding/xml"
	"github.com/hooklift/gowsdl/soap"
	"time"
)

// against "unused imports"
var _ time.Time
var _ xml.Name

type AnyType struct {
	InnerXML string `xml:",innerxml"`
}

type AnyURI string

type NCName string

type EmailAddressType string

const (
	EmailAddressTypeHome EmailAddressType = "Home"

	EmailAddressTypePrimary EmailAddressType = "Primary"

	EmailAddressTypeAlternative EmailAddressType = "Alternative"
)

type FaxNumberType string

const (
	FaxNumberTypePrimary FaxNumberType = "Primary"
)

type Gender string

const (
	GenderNoChange Gender = "NoChange"

	GenderUnknown Gender = "Unknown"

	GenderFemale Gender = "Female"

	GenderMale Gender = "Male"
)

type PhoneNumberType string

const (
	PhoneNumberTypePrimary PhoneNumberType = "Primary"

	PhoneNumberTypeMobile PhoneNumberType = "Mobile"
)

type AddressType string

const (
	AddressTypePost AddressType = "Post"
)

type TriState string

const (
	TriStateNone TriState = "none"

	TriStateTrue TriState = "True"

	TriStateFalse TriState = "False"
)

type GetPersonId struct {
	XMLName xml.Name `xml:"http://24sevenOffice.com/webservices GetPersonId"`

	ConsumerPersonNo string `xml:"consumerPersonNo,omitempty" json:"consumerPersonNo,omitempty"`
}

type GetPersonIdResponse struct {
	XMLName xml.Name `xml:"http://24sevenOffice.com/webservices GetPersonIdResponse"`

	GetPersonIdResult int64 `xml:"GetPersonIdResult,omitempty" json:"GetPersonIdResult,omitempty"`
}

type SavePerson struct {
	XMLName xml.Name `xml:"http://24sevenOffice.com/webservices SavePerson"`

	PersonItem *PersonItem `xml:"personItem,omitempty" json:"personItem,omitempty"`
}

type SavePersonResponse struct {
	XMLName xml.Name `xml:"http://24sevenOffice.com/webservices SavePersonResponse"`

	SavePersonResult int64 `xml:"SavePersonResult,omitempty" json:"SavePersonResult,omitempty"`
}

type GetPersonIdsByUserName struct {
	XMLName xml.Name `xml:"http://24sevenOffice.com/webservices GetPersonIdsByUserName"`

	Username string `xml:"username,omitempty" json:"username,omitempty"`
}

type GetPersonIdsByUserNameResponse struct {
	XMLName xml.Name `xml:"http://24sevenOffice.com/webservices GetPersonIdsByUserNameResponse"`

	GetPersonIdsByUserNameResult *ArrayOfLong `xml:"GetPersonIdsByUserNameResult,omitempty" json:"GetPersonIdsByUserNameResult,omitempty"`
}

type GetPersonIdByCompanyId struct {
	XMLName xml.Name `xml:"http://24sevenOffice.com/webservices GetPersonIdByCompanyId"`

	CompanyId int32 `xml:"companyId,omitempty" json:"companyId,omitempty"`
}

type GetPersonIdByCompanyIdResponse struct {
	XMLName xml.Name `xml:"http://24sevenOffice.com/webservices GetPersonIdByCompanyIdResponse"`

	GetPersonIdByCompanyIdResult int64 `xml:"GetPersonIdByCompanyIdResult,omitempty" json:"GetPersonIdByCompanyIdResult,omitempty"`
}

type GetPersons struct {
	XMLName xml.Name `xml:"http://24sevenOffice.com/webservices GetPersons"`

	PersonSearch *PersonSearchParameters `xml:"personSearch,omitempty" json:"personSearch,omitempty"`
}

type GetPersonsResponse struct {
	XMLName xml.Name `xml:"http://24sevenOffice.com/webservices GetPersonsResponse"`

	GetPersonsResult *ArrayOfPersonItem `xml:"GetPersonsResult,omitempty" json:"GetPersonsResult,omitempty"`
}

type GetPersonsDetailed struct {
	XMLName xml.Name `xml:"http://24sevenOffice.com/webservices GetPersonsDetailed"`

	PersonSearch *PersonSearchParameters `xml:"personSearch,omitempty" json:"personSearch,omitempty"`
}

type GetPersonsDetailedResponse struct {
	XMLName xml.Name `xml:"http://24sevenOffice.com/webservices GetPersonsDetailedResponse"`

	GetPersonsDetailedResult *ArrayOfPersonItem `xml:"GetPersonsDetailedResult,omitempty" json:"GetPersonsDetailedResult,omitempty"`
}

type MakeRelation struct {
	XMLName xml.Name `xml:"http://24sevenOffice.com/webservices MakeRelation"`

	Relation *RelationData `xml:"relation,omitempty" json:"relation,omitempty"`
}

type MakeRelationResponse struct {
	XMLName xml.Name `xml:"http://24sevenOffice.com/webservices MakeRelationResponse"`

	MakeRelationResult bool `xml:"MakeRelationResult,omitempty" json:"MakeRelationResult,omitempty"`
}

type GetRelations struct {
	XMLName xml.Name `xml:"http://24sevenOffice.com/webservices GetRelations"`

	PersonId int64 `xml:"personId,omitempty" json:"personId,omitempty"`
}

type GetRelationsResponse struct {
	XMLName xml.Name `xml:"http://24sevenOffice.com/webservices GetRelationsResponse"`

	GetRelationsResult *ArrayOfRelationData `xml:"GetRelationsResult,omitempty" json:"GetRelationsResult,omitempty"`
}

type GetRelationsChangedAfter struct {
	XMLName xml.Name `xml:"http://24sevenOffice.com/webservices GetRelationsChangedAfter"`

	ChangedAfter soap.XSDDateTime `xml:"changedAfter,omitempty" json:"changedAfter,omitempty"`
}

type GetRelationsChangedAfterResponse struct {
	XMLName xml.Name `xml:"http://24sevenOffice.com/webservices GetRelationsChangedAfterResponse"`

	GetRelationsChangedAfterResult *ArrayOfRelationData `xml:"GetRelationsChangedAfterResult,omitempty" json:"GetRelationsChangedAfterResult,omitempty"`
}

type DeleteRelation struct {
	XMLName xml.Name `xml:"http://24sevenOffice.com/webservices DeleteRelation"`

	PersonId int64 `xml:"personId,omitempty" json:"personId,omitempty"`

	CompanyId int64 `xml:"companyId,omitempty" json:"companyId,omitempty"`
}

type DeleteRelationResponse struct {
	XMLName xml.Name `xml:"http://24sevenOffice.com/webservices DeleteRelationResponse"`
}

type GetNotes struct {
	XMLName xml.Name `xml:"http://24sevenOffice.com/webservices GetNotes"`

	PersonId int64 `xml:"personId,omitempty" json:"personId,omitempty"`
}

type GetNotesResponse struct {
	XMLName xml.Name `xml:"http://24sevenOffice.com/webservices GetNotesResponse"`

	GetNotesResult *ArrayOfNoteData `xml:"GetNotesResult,omitempty" json:"GetNotesResult,omitempty"`
}

type GetAllNotes struct {
	XMLName xml.Name `xml:"http://24sevenOffice.com/webservices GetAllNotes"`
}

type GetAllNotesResponse struct {
	XMLName xml.Name `xml:"http://24sevenOffice.com/webservices GetAllNotesResponse"`

	GetAllNotesResult *ArrayOfNoteData `xml:"GetAllNotesResult,omitempty" json:"GetAllNotesResult,omitempty"`
}

type AddNote struct {
	XMLName xml.Name `xml:"http://24sevenOffice.com/webservices AddNote"`

	Note *NoteData `xml:"note,omitempty" json:"note,omitempty"`
}

type AddNoteResponse struct {
	XMLName xml.Name `xml:"http://24sevenOffice.com/webservices AddNoteResponse"`

	AddNoteResult int32 `xml:"AddNoteResult,omitempty" json:"AddNoteResult,omitempty"`
}

type DeleteNote struct {
	XMLName xml.Name `xml:"http://24sevenOffice.com/webservices DeleteNote"`

	Note *NoteData `xml:"note,omitempty" json:"note,omitempty"`
}

type DeleteNoteResponse struct {
	XMLName xml.Name `xml:"http://24sevenOffice.com/webservices DeleteNoteResponse"`
}

type DeleteNoteById struct {
	XMLName xml.Name `xml:"http://24sevenOffice.com/webservices DeleteNoteById"`

	NoteId int32 `xml:"noteId,omitempty" json:"noteId,omitempty"`
}

type DeleteNoteByIdResponse struct {
	XMLName xml.Name `xml:"http://24sevenOffice.com/webservices DeleteNoteByIdResponse"`
}

type GetCategoryList struct {
	XMLName xml.Name `xml:"http://24sevenOffice.com/webservices GetCategoryList"`
}

type GetCategoryListResponse struct {
	XMLName xml.Name `xml:"http://24sevenOffice.com/webservices GetCategoryListResponse"`

	GetCategoryListResult *ArrayOfCategory `xml:"GetCategoryListResult,omitempty" json:"GetCategoryListResult,omitempty"`
}

type GetPersonCategoryList struct {
	XMLName xml.Name `xml:"http://24sevenOffice.com/webservices GetPersonCategoryList"`

	PersonId int64 `xml:"personId,omitempty" json:"personId,omitempty"`
}

type GetPersonCategoryListResponse struct {
	XMLName xml.Name `xml:"http://24sevenOffice.com/webservices GetPersonCategoryListResponse"`

	GetPersonCategoryListResult *ArrayOfInt `xml:"GetPersonCategoryListResult,omitempty" json:"GetPersonCategoryListResult,omitempty"`
}

type GetPersonArrayCategoryList struct {
	XMLName xml.Name `xml:"http://24sevenOffice.com/webservices GetPersonArrayCategoryList"`

	PersonIds *ArrayOfInt `xml:"personIds,omitempty" json:"personIds,omitempty"`
}

type GetPersonArrayCategoryListResponse struct {
	XMLName xml.Name `xml:"http://24sevenOffice.com/webservices GetPersonArrayCategoryListResponse"`

	GetPersonArrayCategoryListResult *ArrayOfPersonCategories `xml:"GetPersonArrayCategoryListResult,omitempty" json:"GetPersonArrayCategoryListResult,omitempty"`
}

type AddCategoryToPerson struct {
	XMLName xml.Name `xml:"http://24sevenOffice.com/webservices AddCategoryToPerson"`

	PersonId int64 `xml:"personId,omitempty" json:"personId,omitempty"`

	CategoryId int32 `xml:"categoryId,omitempty" json:"categoryId,omitempty"`
}

type AddCategoryToPersonResponse struct {
	XMLName xml.Name `xml:"http://24sevenOffice.com/webservices AddCategoryToPersonResponse"`
}

type RemoveCategoryFromPerson struct {
	XMLName xml.Name `xml:"http://24sevenOffice.com/webservices RemoveCategoryFromPerson"`

	PersonId int64 `xml:"personId,omitempty" json:"personId,omitempty"`

	CategoryId int32 `xml:"categoryId,omitempty" json:"categoryId,omitempty"`
}

type RemoveCategoryFromPersonResponse struct {
	XMLName xml.Name `xml:"http://24sevenOffice.com/webservices RemoveCategoryFromPersonResponse"`
}

type Authentication struct {
	Username string `xml:"Username,omitempty" json:"Username,omitempty"`

	Password string `xml:"Password,omitempty" json:"Password,omitempty"`

	UserId string `xml:"UserId,omitempty" json:"UserId,omitempty"`

	EmployeeId string `xml:"EmployeeId,omitempty" json:"EmployeeId,omitempty"`

	ConsumerId int64 `xml:"ConsumerId,omitempty" json:"ConsumerId,omitempty"`
}

type PersonItem struct {
	Comment string `xml:"Comment,omitempty" json:"Comment,omitempty"`

	ConsumerPersonNo string `xml:"ConsumerPersonNo,omitempty" json:"ConsumerPersonNo,omitempty"`

	Country string `xml:"Country,omitempty" json:"Country,omitempty"`

	CustomerId int32 `xml:"CustomerId,omitempty" json:"CustomerId,omitempty"`

	DateRegistered soap.XSDDateTime `xml:"DateRegistered,omitempty" json:"DateRegistered,omitempty"`

	DateChanged soap.XSDDateTime `xml:"DateChanged,omitempty" json:"DateChanged,omitempty"`

	DateOfBirth soap.XSDDateTime `xml:"DateOfBirth,omitempty" json:"DateOfBirth,omitempty"`

	Department string `xml:"Department,omitempty" json:"Department,omitempty"`

	EmailAddresses *ArrayOfEmailAddress `xml:"EmailAddresses,omitempty" json:"EmailAddresses,omitempty"`

	EmployeeNumber int32 `xml:"EmployeeNumber,omitempty" json:"EmployeeNumber,omitempty"`

	FaxNumber *FaxNumber `xml:"FaxNumber,omitempty" json:"FaxNumber,omitempty"`

	FirstName string `xml:"FirstName,omitempty" json:"FirstName,omitempty"`

	Gender *Gender `xml:"Gender,omitempty" json:"Gender,omitempty"`

	Id int64 `xml:"Id,omitempty" json:"Id,omitempty"`

	LastName string `xml:"LastName,omitempty" json:"LastName,omitempty"`

	Nickname string `xml:"Nickname,omitempty" json:"Nickname,omitempty"`

	PersonalStatus string `xml:"PersonalStatus,omitempty" json:"PersonalStatus,omitempty"`

	PhoneNumbers *ArrayOfPhoneNumber `xml:"PhoneNumbers,omitempty" json:"PhoneNumbers,omitempty"`

	PostAddress *Address `xml:"PostAddress,omitempty" json:"PostAddress,omitempty"`

	RelationData *ArrayOfRelationData `xml:"RelationData,omitempty" json:"RelationData,omitempty"`

	Url string `xml:"Url,omitempty" json:"Url,omitempty"`

	WebPassword string `xml:"WebPassword,omitempty" json:"WebPassword,omitempty"`

	WebUserName string `xml:"WebUserName,omitempty" json:"WebUserName,omitempty"`

	Workplace string `xml:"Workplace,omitempty" json:"Workplace,omitempty"`

	WorkPosition string `xml:"WorkPosition,omitempty" json:"WorkPosition,omitempty"`

	IsPrivate *bool `xml:"IsPrivate,omitempty" json:"IsPrivate,omitempty"`

	HourCost *float64 `xml:"HourCost,omitempty" json:"HourCost,omitempty"`

	EmployeeId *int32 `xml:"EmployeeId,omitempty" json:"EmployeeId,omitempty"`
}

type ArrayOfEmailAddress struct {
	EmailAddress []*EmailAddress `xml:"EmailAddress,omitempty" json:"EmailAddress,omitempty"`
}

type EmailAddress struct {
	Description string `xml:"Description,omitempty" json:"Description,omitempty"`

	Type *EmailAddressType `xml:"Type,omitempty" json:"Type,omitempty"`

	Value string `xml:"Value,omitempty" json:"Value,omitempty"`
}

type FaxNumber struct {
	Description string `xml:"Description,omitempty" json:"Description,omitempty"`

	Type *FaxNumberType `xml:"Type,omitempty" json:"Type,omitempty"`

	Value string `xml:"Value,omitempty" json:"Value,omitempty"`
}

type ArrayOfPhoneNumber struct {
	PhoneNumber []*PhoneNumber `xml:"PhoneNumber,omitempty" json:"PhoneNumber,omitempty"`
}

type PhoneNumber struct {
	Description string `xml:"Description,omitempty" json:"Description,omitempty"`

	Type *PhoneNumberType `xml:"Type,omitempty" json:"Type,omitempty"`

	Value string `xml:"Value,omitempty" json:"Value,omitempty"`
}

type Address struct {
	City string `xml:"City,omitempty" json:"City,omitempty"`

	Country string `xml:"Country,omitempty" json:"Country,omitempty"`

	County string `xml:"County,omitempty" json:"County,omitempty"`

	Description string `xml:"Description,omitempty" json:"Description,omitempty"`

	PostalArea string `xml:"PostalArea,omitempty" json:"PostalArea,omitempty"`

	PostalCode string `xml:"PostalCode,omitempty" json:"PostalCode,omitempty"`

	State string `xml:"State,omitempty" json:"State,omitempty"`

	Street string `xml:"Street,omitempty" json:"Street,omitempty"`

	Type *AddressType `xml:"Type,omitempty" json:"Type,omitempty"`
}

type ArrayOfRelationData struct {
	RelationData []*RelationData `xml:"RelationData,omitempty" json:"RelationData,omitempty"`
}

type RelationData struct {
	ContactId int64 `xml:"ContactId,omitempty" json:"ContactId,omitempty"`

	CustomerId int64 `xml:"CustomerId,omitempty" json:"CustomerId,omitempty"`

	Email string `xml:"Email,omitempty" json:"Email,omitempty"`

	Mobile string `xml:"Mobile,omitempty" json:"Mobile,omitempty"`

	Phone string `xml:"Phone,omitempty" json:"Phone,omitempty"`

	Title string `xml:"Title,omitempty" json:"Title,omitempty"`
}

type ArrayOfLong struct {
	Long []int64 `xml:"long,omitempty" json:"long,omitempty"`
}

type PersonSearchParameters struct {
	ChangedAfter soap.XSDDateTime `xml:"ChangedAfter,omitempty" json:"ChangedAfter,omitempty"`

	ConsumerPersonNo string `xml:"ConsumerPersonNo,omitempty" json:"ConsumerPersonNo,omitempty"`

	CustomerId int64 `xml:"CustomerId,omitempty" json:"CustomerId,omitempty"`

	Email string `xml:"Email,omitempty" json:"Email,omitempty"`

	EmployeeId int32 `xml:"EmployeeId,omitempty" json:"EmployeeId,omitempty"`

	GetRelationData bool `xml:"GetRelationData,omitempty" json:"GetRelationData,omitempty"`

	Id int64 `xml:"Id,omitempty" json:"Id,omitempty"`

	IsEmployee *TriState `xml:"IsEmployee,omitempty" json:"IsEmployee,omitempty"`

	Name string `xml:"Name,omitempty" json:"Name,omitempty"`

	Role string `xml:"Role,omitempty" json:"Role,omitempty"`

	Phone string `xml:"Phone,omitempty" json:"Phone,omitempty"`
}

type ArrayOfPersonItem struct {
	PersonItem []*PersonItem `xml:"PersonItem,omitempty" json:"PersonItem,omitempty"`
}

type ArrayOfNoteData struct {
	NoteData []*NoteData `xml:"NoteData,omitempty" json:"NoteData,omitempty"`
}

type NoteData struct {
	Id int32 `xml:"Id,omitempty" json:"Id,omitempty"`

	Subject string `xml:"Subject,omitempty" json:"Subject,omitempty"`

	Description string `xml:"Description,omitempty" json:"Description,omitempty"`

	EmployeeId int32 `xml:"EmployeeId,omitempty" json:"EmployeeId,omitempty"`

	DateAdded soap.XSDDateTime `xml:"DateAdded,omitempty" json:"DateAdded,omitempty"`

	Date soap.XSDDateTime `xml:"Date,omitempty" json:"Date,omitempty"`

	PersonId int64 `xml:"PersonId,omitempty" json:"PersonId,omitempty"`
}

type ArrayOfCategory struct {
	Category []*Category `xml:"Category,omitempty" json:"Category,omitempty"`
}

type Category struct {
	Id int32 `xml:"Id,omitempty" json:"Id,omitempty"`

	Name string `xml:"Name,omitempty" json:"Name,omitempty"`

	Note string `xml:"Note,omitempty" json:"Note,omitempty"`
}

type ArrayOfInt struct {
	Int []int32 `xml:"int,omitempty" json:"int,omitempty"`
}

type ArrayOfPersonCategories struct {
	PersonCategories []*PersonCategories `xml:"PersonCategories,omitempty" json:"PersonCategories,omitempty"`
}

type PersonCategories struct {
	PersonId int32 `xml:"personId,omitempty" json:"personId,omitempty"`

	Categories *ArrayOfInt `xml:"categories,omitempty" json:"categories,omitempty"`
}

type PersonServiceSoap interface {

	/* Gets 24SevenOffice's Person Id that corresponds to the given Consumer Person Id */
	GetPersonId(request *GetPersonId) (*GetPersonIdResponse, error)

	GetPersonIdContext(ctx context.Context, request *GetPersonId) (*GetPersonIdResponse, error)

	/* Saves a new contact into 24SevenOffice system and returns the id assigned to the new contact */
	SavePerson(request *SavePerson) (*SavePersonResponse, error)

	SavePersonContext(ctx context.Context, request *SavePerson) (*SavePersonResponse, error)

	/* Gets a list of Person Ids from a username in 24SO's system */
	GetPersonIdsByUserName(request *GetPersonIdsByUserName) (*GetPersonIdsByUserNameResponse, error)

	GetPersonIdsByUserNameContext(ctx context.Context, request *GetPersonIdsByUserName) (*GetPersonIdsByUserNameResponse, error)

	/* Gets 24SevenOffice's Person Id that corresponds to the given Company Id */
	GetPersonIdByCompanyId(request *GetPersonIdByCompanyId) (*GetPersonIdByCompanyIdResponse, error)

	GetPersonIdByCompanyIdContext(ctx context.Context, request *GetPersonIdByCompanyId) (*GetPersonIdByCompanyIdResponse, error)

	/* Gets a list of Persons registered as contacts in 24SO's system */
	GetPersons(request *GetPersons) (*GetPersonsResponse, error)

	GetPersonsContext(ctx context.Context, request *GetPersons) (*GetPersonsResponse, error)

	/* Gets a list of Persons registered as contacts in 24SO's system */
	GetPersonsDetailed(request *GetPersonsDetailed) (*GetPersonsDetailedResponse, error)

	GetPersonsDetailedContext(ctx context.Context, request *GetPersonsDetailed) (*GetPersonsDetailedResponse, error)

	/* Makes a relation between a contact and a customer */
	MakeRelation(request *MakeRelation) (*MakeRelationResponse, error)

	MakeRelationContext(ctx context.Context, request *MakeRelation) (*MakeRelationResponse, error)

	/* Gets a list of all relations for a person by PersonId. Notice: Only new authentication method  */
	GetRelations(request *GetRelations) (*GetRelationsResponse, error)

	GetRelationsContext(ctx context.Context, request *GetRelations) (*GetRelationsResponse, error)

	/* Gets a list of all relations for a person by PersonId. Notice: Only new authentication method  */
	GetRelationsChangedAfter(request *GetRelationsChangedAfter) (*GetRelationsChangedAfterResponse, error)

	GetRelationsChangedAfterContext(ctx context.Context, request *GetRelationsChangedAfter) (*GetRelationsChangedAfterResponse, error)

	/* Deletes a relation. Notice: Only new authentication method  */
	DeleteRelation(request *DeleteRelation) (*DeleteRelationResponse, error)

	DeleteRelationContext(ctx context.Context, request *DeleteRelation) (*DeleteRelationResponse, error)

	/* Gets a list of all notes for a Person. Notice: Only new authentication method allowed */
	GetNotes(request *GetNotes) (*GetNotesResponse, error)

	GetNotesContext(ctx context.Context, request *GetNotes) (*GetNotesResponse, error)

	/* Gets a list of all notes for all contact. Notice: Only new authentication method allowed */
	GetAllNotes(request *GetAllNotes) (*GetAllNotesResponse, error)

	GetAllNotesContext(ctx context.Context, request *GetAllNotes) (*GetAllNotesResponse, error)

	/* Adds a note. Notice: Only new authentication method allowed */
	AddNote(request *AddNote) (*AddNoteResponse, error)

	AddNoteContext(ctx context.Context, request *AddNote) (*AddNoteResponse, error)

	/* Deletes a note. Notice: Only new authentication method allowed */
	DeleteNote(request *DeleteNote) (*DeleteNoteResponse, error)

	DeleteNoteContext(ctx context.Context, request *DeleteNote) (*DeleteNoteResponse, error)

	/* Deletes a note by NoteId. Notice: Only new authentication method allowed */
	DeleteNoteById(request *DeleteNoteById) (*DeleteNoteByIdResponse, error)

	DeleteNoteByIdContext(ctx context.Context, request *DeleteNoteById) (*DeleteNoteByIdResponse, error)

	/* Gets the complete list of CRM Categories */
	GetCategoryList(request *GetCategoryList) (*GetCategoryListResponse, error)

	GetCategoryListContext(ctx context.Context, request *GetCategoryList) (*GetCategoryListResponse, error)

	/* Gets a list of Categories for a Person */
	GetPersonCategoryList(request *GetPersonCategoryList) (*GetPersonCategoryListResponse, error)

	GetPersonCategoryListContext(ctx context.Context, request *GetPersonCategoryList) (*GetPersonCategoryListResponse, error)

	/* Gets a list of Categories for an array of Persons */
	GetPersonArrayCategoryList(request *GetPersonArrayCategoryList) (*GetPersonArrayCategoryListResponse, error)

	GetPersonArrayCategoryListContext(ctx context.Context, request *GetPersonArrayCategoryList) (*GetPersonArrayCategoryListResponse, error)

	/* Adds a category to a Person */
	AddCategoryToPerson(request *AddCategoryToPerson) (*AddCategoryToPersonResponse, error)

	AddCategoryToPersonContext(ctx context.Context, request *AddCategoryToPerson) (*AddCategoryToPersonResponse, error)

	/* Removes a category from a Person */
	RemoveCategoryFromPerson(request *RemoveCategoryFromPerson) (*RemoveCategoryFromPersonResponse, error)

	RemoveCategoryFromPersonContext(ctx context.Context, request *RemoveCategoryFromPerson) (*RemoveCategoryFromPersonResponse, error)
}

type personServiceSoap struct {
	client *soap.Client
}

func NewPersonServiceSoap(client *soap.Client) PersonServiceSoap {
	return &personServiceSoap{
		client: client,
	}
}

func (service *personServiceSoap) GetPersonIdContext(ctx context.Context, request *GetPersonId) (*GetPersonIdResponse, error) {
	response := new(GetPersonIdResponse)
	err := service.client.CallContext(ctx, "http://24sevenOffice.com/webservices/GetPersonId", request, response)
	if err != nil {
		return nil, err
	}

	return response, nil
}

func (service *personServiceSoap) GetPersonId(request *GetPersonId) (*GetPersonIdResponse, error) {
	return service.GetPersonIdContext(
		context.Background(),
		request,
	)
}

func (service *personServiceSoap) SavePersonContext(ctx context.Context, request *SavePerson) (*SavePersonResponse, error) {
	response := new(SavePersonResponse)
	err := service.client.CallContext(ctx, "http://24sevenOffice.com/webservices/SavePerson", request, response)
	if err != nil {
		return nil, err
	}

	return response, nil
}

func (service *personServiceSoap) SavePerson(request *SavePerson) (*SavePersonResponse, error) {
	return service.SavePersonContext(
		context.Background(),
		request,
	)
}

func (service *personServiceSoap) GetPersonIdsByUserNameContext(ctx context.Context, request *GetPersonIdsByUserName) (*GetPersonIdsByUserNameResponse, error) {
	response := new(GetPersonIdsByUserNameResponse)
	err := service.client.CallContext(ctx, "http://24sevenOffice.com/webservices/GetPersonIdsByUserName", request, response)
	if err != nil {
		return nil, err
	}

	return response, nil
}

func (service *personServiceSoap) GetPersonIdsByUserName(request *GetPersonIdsByUserName) (*GetPersonIdsByUserNameResponse, error) {
	return service.GetPersonIdsByUserNameContext(
		context.Background(),
		request,
	)
}

func (service *personServiceSoap) GetPersonIdByCompanyIdContext(ctx context.Context, request *GetPersonIdByCompanyId) (*GetPersonIdByCompanyIdResponse, error) {
	response := new(GetPersonIdByCompanyIdResponse)
	err := service.client.CallContext(ctx, "http://24sevenOffice.com/webservices/GetPersonIdByCompanyId", request, response)
	if err != nil {
		return nil, err
	}

	return response, nil
}

func (service *personServiceSoap) GetPersonIdByCompanyId(request *GetPersonIdByCompanyId) (*GetPersonIdByCompanyIdResponse, error) {
	return service.GetPersonIdByCompanyIdContext(
		context.Background(),
		request,
	)
}

func (service *personServiceSoap) GetPersonsContext(ctx context.Context, request *GetPersons) (*GetPersonsResponse, error) {
	response := new(GetPersonsResponse)
	err := service.client.CallContext(ctx, "http://24sevenOffice.com/webservices/GetPersons", request, response)
	if err != nil {
		return nil, err
	}

	return response, nil
}

func (service *personServiceSoap) GetPersons(request *GetPersons) (*GetPersonsResponse, error) {
	return service.GetPersonsContext(
		context.Background(),
		request,
	)
}

func (service *personServiceSoap) GetPersonsDetailedContext(ctx context.Context, request *GetPersonsDetailed) (*GetPersonsDetailedResponse, error) {
	response := new(GetPersonsDetailedResponse)
	err := service.client.CallContext(ctx, "http://24sevenOffice.com/webservices/GetPersonsDetailed", request, response)
	if err != nil {
		return nil, err
	}

	return response, nil
}

func (service *personServiceSoap) GetPersonsDetailed(request *GetPersonsDetailed) (*GetPersonsDetailedResponse, error) {
	return service.GetPersonsDetailedContext(
		context.Background(),
		request,
	)
}

func (service *personServiceSoap) MakeRelationContext(ctx context.Context, request *MakeRelation) (*MakeRelationResponse, error) {
	response := new(MakeRelationResponse)
	err := service.client.CallContext(ctx, "http://24sevenOffice.com/webservices/MakeRelation", request, response)
	if err != nil {
		return nil, err
	}

	return response, nil
}

func (service *personServiceSoap) MakeRelation(request *MakeRelation) (*MakeRelationResponse, error) {
	return service.MakeRelationContext(
		context.Background(),
		request,
	)
}

func (service *personServiceSoap) GetRelationsContext(ctx context.Context, request *GetRelations) (*GetRelationsResponse, error) {
	response := new(GetRelationsResponse)
	err := service.client.CallContext(ctx, "http://24sevenOffice.com/webservices/GetRelations", request, response)
	if err != nil {
		return nil, err
	}

	return response, nil
}

func (service *personServiceSoap) GetRelations(request *GetRelations) (*GetRelationsResponse, error) {
	return service.GetRelationsContext(
		context.Background(),
		request,
	)
}

func (service *personServiceSoap) GetRelationsChangedAfterContext(ctx context.Context, request *GetRelationsChangedAfter) (*GetRelationsChangedAfterResponse, error) {
	response := new(GetRelationsChangedAfterResponse)
	err := service.client.CallContext(ctx, "http://24sevenOffice.com/webservices/GetRelationsChangedAfter", request, response)
	if err != nil {
		return nil, err
	}

	return response, nil
}

func (service *personServiceSoap) GetRelationsChangedAfter(request *GetRelationsChangedAfter) (*GetRelationsChangedAfterResponse, error) {
	return service.GetRelationsChangedAfterContext(
		context.Background(),
		request,
	)
}

func (service *personServiceSoap) DeleteRelationContext(ctx context.Context, request *DeleteRelation) (*DeleteRelationResponse, error) {
	response := new(DeleteRelationResponse)
	err := service.client.CallContext(ctx, "http://24sevenOffice.com/webservices/DeleteRelation", request, response)
	if err != nil {
		return nil, err
	}

	return response, nil
}

func (service *personServiceSoap) DeleteRelation(request *DeleteRelation) (*DeleteRelationResponse, error) {
	return service.DeleteRelationContext(
		context.Background(),
		request,
	)
}

func (service *personServiceSoap) GetNotesContext(ctx context.Context, request *GetNotes) (*GetNotesResponse, error) {
	response := new(GetNotesResponse)
	err := service.client.CallContext(ctx, "http://24sevenOffice.com/webservices/GetNotes", request, response)
	if err != nil {
		return nil, err
	}

	return response, nil
}

func (service *personServiceSoap) GetNotes(request *GetNotes) (*GetNotesResponse, error) {
	return service.GetNotesContext(
		context.Background(),
		request,
	)
}

func (service *personServiceSoap) GetAllNotesContext(ctx context.Context, request *GetAllNotes) (*GetAllNotesResponse, error) {
	response := new(GetAllNotesResponse)
	err := service.client.CallContext(ctx, "http://24sevenOffice.com/webservices/GetAllNotes", request, response)
	if err != nil {
		return nil, err
	}

	return response, nil
}

func (service *personServiceSoap) GetAllNotes(request *GetAllNotes) (*GetAllNotesResponse, error) {
	return service.GetAllNotesContext(
		context.Background(),
		request,
	)
}

func (service *personServiceSoap) AddNoteContext(ctx context.Context, request *AddNote) (*AddNoteResponse, error) {
	response := new(AddNoteResponse)
	err := service.client.CallContext(ctx, "http://24sevenOffice.com/webservices/AddNote", request, response)
	if err != nil {
		return nil, err
	}

	return response, nil
}

func (service *personServiceSoap) AddNote(request *AddNote) (*AddNoteResponse, error) {
	return service.AddNoteContext(
		context.Background(),
		request,
	)
}

func (service *personServiceSoap) DeleteNoteContext(ctx context.Context, request *DeleteNote) (*DeleteNoteResponse, error) {
	response := new(DeleteNoteResponse)
	err := service.client.CallContext(ctx, "http://24sevenOffice.com/webservices/DeleteNote", request, response)
	if err != nil {
		return nil, err
	}

	return response, nil
}

func (service *personServiceSoap) DeleteNote(request *DeleteNote) (*DeleteNoteResponse, error) {
	return service.DeleteNoteContext(
		context.Background(),
		request,
	)
}

func (service *personServiceSoap) DeleteNoteByIdContext(ctx context.Context, request *DeleteNoteById) (*DeleteNoteByIdResponse, error) {
	response := new(DeleteNoteByIdResponse)
	err := service.client.CallContext(ctx, "http://24sevenOffice.com/webservices/DeleteNoteById", request, response)
	if err != nil {
		return nil, err
	}

	return response, nil
}

func (service *personServiceSoap) DeleteNoteById(request *DeleteNoteById) (*DeleteNoteByIdResponse, error) {
	return service.DeleteNoteByIdContext(
		context.Background(),
		request,
	)
}

func (service *personServiceSoap) GetCategoryListContext(ctx context.Context, request *GetCategoryList) (*GetCategoryListResponse, error) {
	response := new(GetCategoryListResponse)
	err := service.client.CallContext(ctx, "http://24sevenOffice.com/webservices/GetCategoryList", request, response)
	if err != nil {
		return nil, err
	}

	return response, nil
}

func (service *personServiceSoap) GetCategoryList(request *GetCategoryList) (*GetCategoryListResponse, error) {
	return service.GetCategoryListContext(
		context.Background(),
		request,
	)
}

func (service *personServiceSoap) GetPersonCategoryListContext(ctx context.Context, request *GetPersonCategoryList) (*GetPersonCategoryListResponse, error) {
	response := new(GetPersonCategoryListResponse)
	err := service.client.CallContext(ctx, "http://24sevenOffice.com/webservices/GetPersonCategoryList", request, response)
	if err != nil {
		return nil, err
	}

	return response, nil
}

func (service *personServiceSoap) GetPersonCategoryList(request *GetPersonCategoryList) (*GetPersonCategoryListResponse, error) {
	return service.GetPersonCategoryListContext(
		context.Background(),
		request,
	)
}

func (service *personServiceSoap) GetPersonArrayCategoryListContext(ctx context.Context, request *GetPersonArrayCategoryList) (*GetPersonArrayCategoryListResponse, error) {
	response := new(GetPersonArrayCategoryListResponse)
	err := service.client.CallContext(ctx, "http://24sevenOffice.com/webservices/GetPersonArrayCategoryList", request, response)
	if err != nil {
		return nil, err
	}

	return response, nil
}

func (service *personServiceSoap) GetPersonArrayCategoryList(request *GetPersonArrayCategoryList) (*GetPersonArrayCategoryListResponse, error) {
	return service.GetPersonArrayCategoryListContext(
		context.Background(),
		request,
	)
}

func (service *personServiceSoap) AddCategoryToPersonContext(ctx context.Context, request *AddCategoryToPerson) (*AddCategoryToPersonResponse, error) {
	response := new(AddCategoryToPersonResponse)
	err := service.client.CallContext(ctx, "http://24sevenOffice.com/webservices/AddCategoryToPerson", request, response)
	if err != nil {
		return nil, err
	}

	return response, nil
}

func (service *personServiceSoap) AddCategoryToPerson(request *AddCategoryToPerson) (*AddCategoryToPersonResponse, error) {
	return service.AddCategoryToPersonContext(
		context.Background(),
		request,
	)
}

func (service *personServiceSoap) RemoveCategoryFromPersonContext(ctx context.Context, request *RemoveCategoryFromPerson) (*RemoveCategoryFromPersonResponse, error) {
	response := new(RemoveCategoryFromPersonResponse)
	err := service.client.CallContext(ctx, "http://24sevenOffice.com/webservices/RemoveCategoryFromPerson", request, response)
	if err != nil {
		return nil, err
	}

	return response, nil
}

func (service *personServiceSoap) RemoveCategoryFromPerson(request *RemoveCategoryFromPerson) (*RemoveCategoryFromPersonResponse, error) {
	return service.RemoveCategoryFromPersonContext(
		context.Background(),
		request,
	)
}
