openapi: 3.0.3
info:
  title: 24SevenOffice Public API
  version: 0.33.1
servers:
  - url: https://rest.api.24sevenoffice.com/v1
paths:
  /accountbalances:
    get:
      summary: Read account balances
      description: Read a list of account balances with monthly changes for a defined period.
      tags:
        - accountbalances
      security:
        - tfso:
            - api.accounting.transaction.accountbalance:read
            - api.accounting.account:read
  /accountbalances/{id}:
    get:
      summary: Read an account balance by ID
      description: Read a list of account balances with monthly changes for a defined period for a specific account identified by its unique ID.
      tags:
        - accountbalances
      security:
        - tfso:
            - api.accounting.transaction.accountbalance:read
            - api.accounting.account:read
  /accounts:
    get:
      tags:
        - accounts
      security:
        - tfso:
            - api.accounting.account:read
      summary: Read accounts
      description: Read a list of accounts, including their details.
  /accounts/{id}:
    get:
      summary: Read an account by ID
      description: Read details of a specific account identified by its unique ID.
      tags:
        - accounts
      security:
        - tfso:
            - api.accounting.account:read
  /currencies:
    get:
      summary: Read currencies
      description: Read a list of available currencies within 24SevenOffice accounting module.
      tags:
        - currencies
      security:
        - tfso: []
  /fiscalperiods:
    get:
      summary: Read fiscal periods
      description: Read a list of fiscal periods.
      tags:
        - fiscalPeriods
      security:
        - tfso:
            - api.accounting.fiscalperiod:read
  /taxes:
    get:
      summary: Read tax codes
      description: Read a list of tax codes available in the accounting system.
      tags:
        - Taxes
      security:
        - tfso:
            - api.accounting.tax:read
  /taxes/{id}:
    get:
      summary: Read a tax code by ID
      description: Read details of a specific tax code identified by its unique ID.
      tags:
        - Taxes
      security:
        - tfso:
            - api.accounting.tax:read
  /transactionlines:
    get:
      summary: Read transaction lines
      description: Read a list of transaction lines for a defined period, based on various filtering criteria.
      tags:
        - transactionLines
      security:
        - tfso:
            - api.accounting.transaction:read
  /transactionlines/{id}:
    get:
      summary: Read a transaction line by ID
      description: Read a single transaction line identified by its unique ID.
      tags:
        - transactionLines
      security:
        - tfso:
            - api.accounting.transaction:read
  /transactiontypes:
    get:
      summary: Read transaction types
      description: Read a list of available transaction types within 24SevenOffice accounting module.
      tags:
        - transactionTypes
      security:
        - tfso:
            - api.accounting.transactiontype:read
            - api.accounting.transaction:read
  /bankaccounts:
    get:
      tags:
        - bankAccounts
      summary: Read bank accounts
      description: Read a list of bank accounts with details. Each bank account includes information such as account number, BIC, type, name, owner details, creation timestamp, modification timestamp, and the latest balance information, should there be one available.
      security:
        - tfso:
            - api.bank.account:read
    post:
      tags:
        - bankAccounts
      summary: Create a bank account
      description: Create a new bank account record with specified details including account number, BIC, type, name, owner details, and optional initial balance information.
      security:
        - tfso:
            - api.bank.account:write
  /bankaccounts/{id}:
    get:
      tags:
        - bankAccounts
      summary: Read a bank account by ID
      description: Read details for a specific bank account identified by its unique identifier. The response includes information such as account number, BIC, type, name, owner details, creation timestamp, modification timestamp, and the latest balance information, should there be one available.
      security:
        - tfso:
            - api.bank.account:read
  /bankaccounts/{id}/balances:
    post:
      tags:
        - bankAccounts
      summary: Create a new bank account balance
      description: Add a new balance entry for a specific bank account identified by its unique identifier. The balance entry includes the amount, timestamp, and currency code. The endpoint facilitates accurate tracking of the bank account's financial status over time.
      security:
        - tfso:
            - api.bank.account:write
  /banktransactions:
    get:
      tags:
        - bankTransactions
      summary: Read bank transactions
      description: |
        Read a list of bank transactions based on specified filters. Each transaction includes details such as transaction reference, type, bank account details, payment reference, amount, date, and status.
      security:
        - tfso:
            - api.bank.transaction:read
    post:
      tags:
        - bankTransactions
      summary: Create a new bank transaction
      description: |
        The `bankAccount.id` is a required property. Before creating bank transaction, a bank account must exists. See `POST /bankaccounts`

        When creating a bank transaction, the backend system loads the existing bank account record using `bankAccount.id`. Information from the bank account is then appended to the bank transaction based on the transaction's direction type (inbound or outbound).

        * For outbound transactions, the `fromBankAccount` field is automatically populated from the specified bank account.
        * For inbound transactions, the `toBankAccount` field is automatically populated from the specified bank account.

        Note: When these fields are automatically set, any input provided in these properties will be ignored.
      security:
        - tfso:
            - api.bank.transaction:write
  /banktransactions/{bankTransactionReference}:
    get:
      tags:
        - bankTransactions
      summary: Read a bank transaction by bank transaction reference
      description: Read details of a specific bank transaction identified by its unique bank transaction reference supplied by the bank.
      security:
        - tfso:
            - api.bank.transaction:read
  /customers:
    get:
      summary: Read customers
      description: Read a list of all customers, including their details, with pagination, or a subset of customers based on query parameters. Whether a customer is a company or a private person is controlled by "isCompany" flag property. The schemas are also slightly different for a company (no "person" property) or a person (no "organizationNumber").
      tags:
        - Customers
      operationId: GetCustomers
      security:
        - tfso:
            - api.crm.customer:read
    post:
      summary: Create a customer
      description: |
        Create a new customer record for a company or a person, and get the newly created customer in return. 

        For a new company customer, define "name" property and set "isCompany" flag to true in the request body. For a new private person customer, define "firstName" and "lastName" under the "person" property, and set "isCompany" flag to false in the request body. These are the minimum required properties that should be defined in the request body for creating a new customer. 

        All other properties for a customer (see response attributes for each property description) can also be defined in the request body, except for "person" when a new customer is a company, and "organizationNumber" and "name" (this one is generated from "firstName" and "lastName" under the "person" property) when a new customer is a person.
      tags:
        - Customers
      operationId: CreateCustomer
      security:
        - tfso:
            - api.crm.customer:write
  /customers/{id}:
    get:
      summary: Read a customer by ID
      description: Read details of a specific customer identified by its unique ID.
      tags:
        - Customers
      security:
        - tfso:
            - api.crm.customer:read
    patch:
      summary: Update a customer
      description: |
        Update details of a specific customer identified by its uinque customer ID, and receive the updated details in return.
      tags:
        - Customers
      operationId: UpdateCustomer
      security:
        - tfso:
            - api.crm.customer:write
    delete:
      summary: Delete a customer
      description: Delete a specific customer identified by its unique ID.
      tags:
        - Customers
      security:
        - tfso:
            - api.crm.customer:write
  /dimensions:
    get:
      description: List all dimension-types. Get a list of all dimension-types in the system. Elements with id below 100 are system dimension-types and will be the same across all clients. Elements with id above 100 are custom dimension-types specific to the client.
      tags:
        - Dimensions
      security:
        - tfso:
            - api.accounting.dimension:read
  /dimensions/{dimensionType}:
    get:
      description: List single dimension-type. Get description of a single dimension-type by id.
      tags:
        - Dimensions
      security:
        - tfso:
            - api.accounting.dimension:read
  /dimensions/{dimensionType}/elements:
    get:
      description: |
        List dimension elements.
        Get a list of active dimension elements for a specific dimension type.
        If there are many elements, the results will be paginated, and a Link-header with rel=next will provide the path to the next page.
      tags:
        - Dimensions
      security:
        - tfso:
            - api.accounting.dimension:read
  /dimensions/{dimensionType}/elements/{value}:
    get:
      description: List single dimension element. Get a single dimension element by dimension type (id) and value (id).
      tags:
        - Dimensions
      security:
        - tfso:
            - api.accounting.dimension:read
  /salesorders:
    post:
      summary: Create a sales order
      description: Create a new sales order with customer details and order information.
      security:
        - tfso:
            - api.invoicing.salesorder:write
    get:
      summary: Read sales orders
      description: Read existing sales orders with optional filters.
      security:
        - tfso:
            - api.invoicing.salesorder:read
  /salesorders/{id}:
    get:
      summary: Read a sales order by ID
      description: Read details of a specific sales order identified by its unique ID.
      security:
        - tfso:
            - api.invoicing.salesorder:read
    patch:
      summary: Update a sales order
      description: Update details of a specific sales order identified by its unique sales order ID, and receive the updated details in return. An existing sales order can be invoiced by updating its `status` to "Invoice". Before a sales order can be invoiced, it needs to include at least one sales order line.
      security:
        - tfso:
            - api.invoicing.salesorder:write
  /salesorders/{id}/attachments:
    get:
      summary: Read sales order attachments
      description: Read all attachments associated with a specific sales order.
      security:
        - tfso:
            - api.invoicing.salesorder.attachment:read
    post:
      summary: Add an attachment to a sales order
      description: Add a new attachment to a specific sales order. The filename should be specified in the `Content-Disposition` header, and the `Content-Type` header must reflect the MIME type of the attachment being uploaded. The file itself should be included in the request body, and should be less than 4 MB in size.
      security:
        - tfso:
            - api.invoicing.salesorder.attachment:write
  /salesorders/{id}/lines:
    get:
      summary: Read sales order lines
      description: Read all lines associated with a specific sales order.
      security:
        - tfso:
            - api.invoicing.salesorder.line:read
    post:
      summary: Create a sales order line
      description: Add a new line to a specific sales order.
      security:
        - tfso:
            - api.invoicing.salesorder.line:write
  /salesorders/{id}/lines/{lineId}:
    get:
      summary: Read a sales order line by ID
      description: Read a specific line from a sales order by the line's ID.
      security:
        - tfso:
            - api.invoicing.salesorder.line:read
    patch:
      summary: Update a sales order line
      description: Update the details of a specific line in a sales order.
      security:
        - tfso:
            - api.invoicing.salesorder.line:write
  /me:
    get:
      summary: Read profile
      description: |
        Read information about the current profile. This endpoint is only available for access tokens that have the identityId claim.

        24SevenOffice is a multi-tenant application, where a personal login gives access to more than one organization and its people. 

        Hence, there exist "identity", "organization" and the organization’s "people".

        ==Identity== → *Organization → *Person

        > info
        > Identity
        > An `identity` is a personal user who logs into 24SevenOffice. An `identity` will have one or more unique identifiers for the personal user, such as an email or a phone number
        > An `identity` may or may not have access to one or more organizations through a person.

        24SevenOffice has a global identity pool where an identity may have access to all organizations available in 24SevenOffice.
      tags:
        - Profile
      security:
        - tfso:
            - api.me.profile:read
  /me/identifiers:
    get:
      summary: Read identifiers
      description: Read identifiers for a profile, where identifiers, such as an email and a phone, may or may not be verified.
      tags:
        - Profile
      security:
        - tfso:
            - api.me.identifiers:read
  /me/identifiers/{id}:
    get:
      summary: Read an identifier by ID
      description: Read details of a specific identifier identified by its unique ID.
      tags:
        - Profile
      security:
        - tfso:
            - api.me.identifiers:read
  /me/licenses:
    get:
      summary: Read licenses
      description: Read all licenses for a profile. Receive in return the identifiers for an organization and the connected person within that company. This information can be used as a login hint to get an access token for operational work on behalf of the connected person.
      tags:
        - Profile
      operationId: GetLicenses
      security:
        - tfso:
            - api.me.license:read
  /me/licenses/{id}/organization:
    get:
      summary: Read an organization by license ID
      description: Read a summary of the organization connected to a license identified by its unique license ID. This summary provides more information than just the organization name, and is useful for looking up details about all connected licenses without authorization from other organizations with login hints.
      tags:
        - Profile
      security:
        - tfso:
            - api.organization.information:read
  /organization/information:
    get:
      summary: Read organization
      description: |
        Read information about the organization that the current profile is logged into. 

        24SevenOffice is a multi-tenant application, where a personal login gives access to more than one organization and its people.

        Hence, there exist "identity", "organization" and the organization’s "people".

        Identity → ==*Organization== → *Person

        > info
        > Organization
        > An `organization` is usually a legal entity based in a certain country. An organization will own all of its data such as customers, invoices, transactions, etc.
        > An `organization` will have many people that may be employees, connections, etc.
      tags:
        - Organization
      operationId: GetClient
      security:
        - tfso:
            - api.organization.information:read
  /organization/people:
    get:
      summary: Read people
      description: |
        Read a list of all people under the organization.

        24SevenOffice is a multi-tenant application, where a personal login gives access to more than one organization and its people. 

        Hence, there exist "identity", "organization" and the organization’s "people".

        Identity → *Organization → ==*Person==

        > info
        > People
        > A `person` is owned by an `organization`, and will usually be an employee or an owner of the `organization`. 
        > A `person` may be connected to an `identity`. 
        > An `identity` connected to a `person` may have a certain role in an `organization`, that will result in a set of permissions called `scopes`.
      tags:
        - Organization
      security:
        - tfso:
            - api.organization.person:read
  /organization/people/{id}:
    get:
      summary: Read a person
      description: Read information about a single person identified by its unique ID.
      tags:
        - Organization
      security:
        - tfso:
            - api.organization.person:read
  /productcategories:
    get:
      summary: Read product categories
      description: Read a list of product categories.
      tags:
        - ProductCategory
      operationId: GetCategories
      security:
        - tfso:
            - api.product.category:read
    post:
      summary: Create a product category
      description: Create a new product category with specified attributes and receive the details of the newly created category in the response.
      tags:
        - ProductCategory
      operationId: CreateCategory
      security:
        - tfso:
            - api.product.category:write
  /productcategories/{id}:
    get:
      summary: Read a product category by ID
      description: Read details of a specific product category identified by its unique ID.
      tags:
        - ProductCategory
      security:
        - tfso:
            - api.product.category:read
    patch:
      summary: Update a product category
      description: Update details of a specific product category identified by its unique ID, and receive the updated details in return.
      tags:
        - ProductCategory
      operationId: UpdateCategory
      security:
        - tfso:
            - api.product.category:write
    delete:
      summary: Delete a product category
      description: Delete a specific product category identified by its unique ID.
      tags:
        - ProductCategory
      operationId: DeleteCategory
      security:
        - tfso:
            - api.product.category:write
  /productunits:
    get:
      summary: Read product units
      description: Read a list of available units of measurement for products.
      tags:
        - ProductUnits
      operationId: GetUnits
      security:
        - tfso:
            - api.product.unit:read
  /products:
    get:
      summary: Read products
      description: Read a list of products, including their details, with pagination, or a subset of products based on query parameters. Products may have different attributes such as name, description, price, and stock information. The endpoint supports various search criteria for filtering products based on specific attributes.
      tags:
        - Products
      operationId: GetProducts
      security:
        - tfso:
            - api.product.product:read
    post:
      summary: Create a product
      description: |
        Create a new product record with specified attributes and receive the details of the newly created product in the response.
      tags:
        - Products
      operationId: CreateProduct
      security:
        - tfso:
            - api.product.product:write
  /products/{id}:
    get:
      summary: Read a product by ID
      description: Read details of a specific product identified by its unique ID.
      tags:
        - Products
      security:
        - tfso:
            - api.product.product:read
    patch:
      summary: Update a product
      description: |
        Update details of a specific product identified by its unique product ID, and receive the updated details in return.
      tags:
        - Products
      operationId: UpdateProduct
      security:
        - tfso:
            - api.product.product:write
    delete:
      summary: Delete a product
      description: Delete a specific product identified by its unique ID.
      tags:
        - Products
      operationId: DeleteProduct
      security:
        - tfso:
            - api.product.product:write
  /salestypes:
    get:
      summary: Read sales types
      description: Read a list of sales types available in the system.
      security:
        - tfso:
            - api.product.salestype:read
  /salestypes/{id}:
    get:
      summary: Read sales type by ID
      description: Read details of a specific sales type by its ID.
      security:
        - tfso:
            - api.product.salestype:read
components:
  securitySchemes:
    tfso:
      type: apiKey
      name: Authorization
      in: header
x-topics:
  - title: Welcome
    content: |
      Welcome to 24SevenOffice API documentation!

      We are excited to announce that we are gradually releasing new API endpoints for public access. Our REST API is designed to provide developers with a simple and secure way to integrate with our platform and access our services.

      By leveraging 24SevenOffice API, you can build integrations, custom applications, automate workflows, and access data in real-time. We believe that our API will help you create innovative solutions based on 24SevenOffice products and enhance the overall user experience.

      Please note that we will be rolling out new API endpoints over time, and not all endpoints will be available for public access at once. Our team is committed to providing high-quality, reliable API that meet the needs of our developer community. As we continue to develop and release new endpoints, we will keep you informed through our API documentation and other communication channels.

      We encourage you to explore our API documentation, which provides detailed information about each endpoint, including how to authenticate, make requests, and handle responses. 

      We do our best to make sure that this documentation has everything you need to help you get started quickly and make good use of our API. Please do not hesitate to contact API Team, should you feel like something is off. 

      We are thrilled to have you on board and look forward to seeing what you are about to create with 24SevenOffice API!
  - title: Get Started
    content: |

      To initiate your journey with the 24SevenOffice API, follow these steps:

      **Step 1: Request Access**

      Locate your 24SevenOffice Client ID for the organization you intend to request access for. Keep this Client ID on hand and complete the access request form by visiting [this link](https://forms.office.com/e/eKGahcT804).

      *How to find Client ID:*
        * *Log in to 24SevenOffice under the organization that will own your integrations.*
        * *Navigate to Accounting and then either:*
          * *Go to [Manage vouchers](https://app.24sevenoffice.com/modules/accounting/vouchers), where you can find the Client ID. The Client ID is the number preceding "@voucher.24sevenoffice.com" at the top-right corner.*
          * *Alternatively, go to Administration > Settings > Retrieval, and find the Client ID next to "@voucher.24sevenoffice.com" there.*

      **Step 2: Enable Developer Admin Panel**

      After we review your request and approve it, the Developer Admin Panel will be activated for your organization's account with the specified Client ID.

      **Step 3: Create Your First Application**

      Head over to the [Developer Admin Panel](https://app.24sevenoffice.com/modules/applicationadmin/applications). Here, you can create your inaugural application, define its scopes, obtain the necessary credentials for acquiring an access token, and kickstart your integration with our API in no time.

      If you have any questions or issues during the setup process, please do not hesitate to contact API Team for assistance. 
  - title: Authentication
    content: |
      To authenticate requests to 24SevenOffice API, users must create an OAuth2 application in our system and obtain client ID and client secret. 

      In addition to client ID and client secret, users must also obtain an organization ID for which the application is granted access to. This is because 24SevenOffice is a multi-tenant application, where a personal login gives access to more than one organization and its people. Please, refer to each of the endpoints for [Identity](/doc/v1/operation/operation-get-me), [Organization](/doc/v1/operation/operation-getclient), and [People](/doc/v1/operation/operation-get-organization-people) in 24[...] 

      The application will then use these credentials (client ID, organization ID, and client secret) to obtain an access token for the user. The process of getting an access token follows OAuth 2.0 Client Credentials Flow (explained in details here: https://auth0.com/docs/get-started/authentication-and-authorization-flow/client-credentials-flow)

      Users must include this access token in the Authorization header of all requests over HTTPS. 

      If the access token is not valid or has expired, the API will respond with an HTTP 401 Unauthorized error, indicating that the request is not authorized.
  - title: Scopes
    content: |
      Scopes refer to the specific areas or actions within the system that users or applications are authorized to access or perform. These scopes are organized into sets of permissions, which are then grouped into predefined sets called roles. 

      Our API provides fine-grained access control that allows users and applications to interact with the system in a secure and controlled manner. However, it is important to note that when requesting access to specific scopes, you may end up with less scopes than you asked for. Therefore, it is essential to handle the 403 error response and adapt the features available to your integration accordingly.  
  - title: Get Access Token
    content: |
      To acquire an access token and initiate your first API call, follow these steps:

      Before you begin, ensure that you have the [Developer Admin Panel](https://app.24sevenoffice.com/modules/applicationadmin/applications) enabled for your account. You should locate a button labeled “Developer” (or “Utvikler” in Norwegian) at the bottom of the main navigation left-side menu on the 24SevenOffice Home page.

      > info
      > If you do not have the Developer admin panel enabled, contact the 24SevenOffice API team.

      1) Log in to the [Developer Admin Panel](https://app.24sevenoffice.com/modules/applicationadmin/applications) and select Create Application.

      2) Complete the required application details, then click Create.

      3) Once the new OAuth2 application is created, click Configure to view the application credentials.

      4) Navigate to Scopes, choose the necessary scopes from the dropdown list, and save changes.

      5) Proceed to Settings and copy the Application ID.

      6) Authorize the application to access your organization's user account details based on the previously selected scopes. To do this, visit the 24SevenOffice Home page and select Integrations under Administration in the main navigation left-side menu. You will be redirected to the [Integrations Admin Panel](https://app.24sevenoffice.com/modules/applicationadmin/integrations) where you manage integrations for your organization account. Click Connect Application.

      7) Paste the Application ID, accept terms of usage and scopes. The application is now connected to your organization's account.

      8) You are now prepared to obtain an access token for your organization. Utilize the application's credentials (application ID/client ID and client secret) along with login hints for the organization. You can find the application's credentials in the [Developer Admin Panel](https://app.24sevenoffice.com/modules/applicationadmin/applications), and the login hint for the organization is usually provided by your future integration users. Your organization has already been connected in step 7 [...] 

      > info
      > **The endpoint for obtaining an authentication token is: `POST https://login.24sevenoffice.com/oauth/token`**  

      9) Define the application's `client_id`, `client_secret`, and `login_organization`. To access `client_id` and `client_secret`, navigate to the [Developer Admin Panel](https://app.24sevenoffice.com/modules/applicationadmin/applications) and click Configure for the application. For `client_id`, insert the value from "Application ID / Client ID" and for `client_secret`, insert the value from Client Secret. 

      An access token is associated with an organization account. To obtain an access token tied to your organization account, visit the [Integrations Admin Panel](https://app.24sevenoffice.com/modules/applicationadmin/integrations), click Configure for the application connected to your organization's account, and from the Info section, copy the Organization ID to paste it for `login_organization`.

      10) Finally, send an API request with all the credentials and receive an access token in the response body.

      > info
      > The access token is valid for a single organization. If you intend to access multiple organizations, steps 6 to 10 should be repeated for each organization.

      To obtain an authentication token for accessing 24SevenOffice REST API resources, you can utilize your code, development environment (Visual Studio, JetBrains, etc.) extensions, or employ API tools like Postman. You can also explore the 24SevenOffice playground at [https://tfso.github.io/publicapi/playground/](https://tfso.github.io/publicapi/playground/) using the [OAuth 2.0 Client Credentials Flow](https://auth0.com/docs/flows/concepts/client-credentials).

      For the purpose of further demonstration, we proceed with Postman. Access Postman here: [https://www.postman.com/](https://www.postman.com/)
      If you are new to Postman, refer to this guide to help you get started: [Postman Overview](https://learning.postman.com/docs/introduction/overview/)

      Include your application's credentials in the request body. A convenient way to do this in Postman is by switching to "x-www-form-urlencoded", enabling Bulk Edit mode, and pasting the following:
      ```
      grant_type:client_credentials
      audience:https://api.24sevenoffice.com
      client_id: [insert from Application ID / Client ID]
      client_secret: [insert from Client Secret]
      login_organization: [insert from Organization ID]
      ```
      Now, send the request and receive an access token in the response body.
  - title: Status & Errors
    content: |
      Our API returns status codes and error responses to help developers understand the outcome of their requests and troubleshoot issues that may arise. 

      Here are the most commonly used status codes and error responses:

      * `200 OK` - The request was successful and the server was able to return the requested data.

      * `201 Created` - The request has been fulfilled and a new resource has been created.

      * `204 No Content` - The request was successful, but there is no response data to return.

      * `400 Bad Request` - The request was malformed or invalid and the server cannot process it.

      * `401 Unauthorized` - The user is not authenticated and the request cannot be processed until they are.

      * `403 Forbidden` - The user is authenticated, but they do not have permission to access the requested resource.

      * `404 Not Found` - The requested resource could not be found on the server.

      * `500 Internal Server Error` - There was an error on the server while processing the request.

      * `503 Service Unavailable` - The server is temporarily unavailable and unable to process the request.

      Please note that each status code may come with additional information in the response body to help developers understand what went wrong and how to resolve the issue. We recommend reviewing the response body for each status code to get a better understanding of the error message.
  - title: Rate limiting
    content: |
      We implement rate limiting to ensure fair usage and protect the stability and reliability of 24SevenOffice API. 

      Rate limiting refers to the practice of limiting the number of requests that can be made to the API within a certain time period. This helps prevent excessive usage that could potentially overload the system or cause performance issues.

      Our API sets a limit on the number of requests that can be made within a given time period, usually measured in seconds or minutes. Once this limit is reached, further requests will be denied until the next time period begins.

      To avoid rate limiting, we recommend that developers implement efficient coding practices and make use of caching to reduce the number of requests made to the API. If you do encounter rate limiting, please wait until the next time period begins before making further requests.

      Please contact our API team for specific rate limit information, as it may vary depending on the API endpoint or resource.
  - title: Versioning
    content: |
      Each version of 24SevenOffice API is identified by a version number, which is included in the URL of the endpoint. This allows you to specify which version of the API you want to use in your requests.

      As we make updates and improvements to our API, we will release new versions to ensure backward compatibility. This means that your existing integrations will continue to work, even as we introduce new features and functionality.

      You must specify a version number when making requests to our API to ensure that your application continues to function as expected. You can find the latest version of our API in our API documentation, and we will also notify you of any upcoming changes or new versions via our communication channels.

      Please note that older versions of our API may eventually be deprecated and no longer supported. We will provide advance notice of any deprecation and work with you to ensure a smooth transition to the latest version.
